# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the project
FROM node:lts-alpine AS builder
WORKDIR /app

# Install build dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci
RUN npm run compile

# Stage 2: Production image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy runtime artifacts and default config
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
COPY example.jailbreak.mcp.json ./config.json

# Install only production dependencies
RUN npm ci --omit=dev

# Use stdio transport by default with provided config
ENTRYPOINT ["node", "dist/index.js", "./config.json"]
