# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY tsconfig.json .
COPY src ./src
RUN npm run compile
# dist is generated in compile, no need to copy src now
COPY example.jailbreak.mcp.json /app/example.jailbreak.mcp.json
CMD ["node", "dist/index.js"]
